version: '3.8'

services:

  postgres:
    image: postgres:15
    build:
      context: .
      dockerfile: Dockerfile.postgresql
    container_name: file-processing-db
    restart: always
    environment:
      POSTGRES_USER: userFile
      POSTGRES_PASSWORD: passFile
      POSTGRES_DB: file_processing
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      
  # app:
  #   build: .
  #   container_name: file-processing
  #   restart: always
  #   depends_on:
  #     - postgres
  #     - redis
  #   env_file:
  #     - .env
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - .:/app
  #   command: npm run start

  redis:
    image: redis:7
    container_name: fiile-processing-redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  postgres_data:
