version: '3.8'

services:

  postgres:
    image: postgres:15
    container_name: file-processing-db
    restart: always
    environment:
      POSTGRES_USER: userFile
      POSTGRES_PASSWORD: passFile
      POSTGRES_DB: file_processing
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  # app:
  #   build: .
  #   container_name: file-processing
  #   restart: always
  #   depends_on:
  #     - postgres
  #     - redis
  #   env_file:
  #     - .env
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - .:/app
  #   command: npm run start

  redis:
    image: redis:7
    container_name: fiile-processing-redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  postgres_data:
